
project_id = "jlqhpccootrwvslvstdm"
[api]
enabled = true
port = 54321
schemas = []
extra_search_path = ["public", "extensions"]
[db]
port = 54322
shadow_port = 54320
[studio]
port = 54323
[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326
[auth]
enabled = true
port = 9999
[realtime]
enabled = false
[storage]
enabled = true
file_size_limit = "50MiB"
[edge_functions]
enabled = true
