// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlqhpccootrwvslvstdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpscWhwY2Nvb3Ryd3ZzbHZzdGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NTU3OTYsImV4cCI6MjA1ODUzMTc5Nn0.wVeVnhWj3E3f25P9dOIm-fb4wD14Mad1bjFnvTaYGrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);